 ✖️ Generador Interactivo de Tablas de Multiplicar

Este proyecto genera la tabla de multiplicar del 1 al 10 para cualquier número que ingrese el usuario.

🔧 Funcionalidades

El usuario ingresa un número.
El programa muestra la tabla de multiplicar del 1 al 10.
Al final, pregunta si desea ver otra tabla:
  Si responde "sí", repite el proceso.
  Si responde "no", finaliza el programa.


Diagrama de flujo:

[INICIO]
|
[Pedir número del cual necesita la tabla de multiplicar al usuario]
|
[Generar y mostrar tabla del numero ingresado y sus multiplicaciones del 1 al 10]
|
[preguntar al usuario si reuiere ver una tabla de un numero diferente]
|
├── SÍ → [Volver a pedir número]
|
└── NO → [Mostrar mensaje de despedida]
